// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MoConfigCard: typeof import('./src/components/MoConfigCard.vue')['default']
    MoInfoCard: typeof import('./src/components/MoInfoCard.vue')['default']
    MoMDContent: typeof import('./src/components/MoMDContent.vue')['default']
    MoMDSideMenu: typeof import('./src/components/MoMDSideMenu.vue')['default']
    MoSearch: typeof import('./src/components/MoSearch.vue')['default']
    MoTagList: typeof import('./src/components/MoTagList.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
