// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MoMarkdown: typeof import('./src/components/moMarkdown.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NInput: typeof import('naive-ui')['NInput']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NSpace: typeof import('naive-ui')['NSpace']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
